compatibility_date = "2022-06-06"

kv_namespaces = [
  { binding = "POAPS" },
  { binding = "POAP_LISTS" },
  { binding = "POAP_CLAIMS" },
  { binding = "POAP_CODES" },
]

# [durable_objects]
# bindings = [
#   { name = "DO", class_name = "Do" }
# ]