name = "poapplesauce"
main = "worker-site/worker.mjs"
usage_model = "bundled"
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-06-30"

kv_namespaces = [
  { binding = "POAPS", id = "2cb8caaa6edd4cb4b60bf6c9a0c3efad" },
  { binding = "POAP_LISTS", id = "60111bbb7d35462e90ff38bb606abf0c" },
  { binding = "POAP_CLAIMS", id = "396d1a233ebd4faf95625ffe8cadd167" },
  { binding = "POAP_CODES", id = "d9729ee754674174b148fece96782106" }
]

routes = [
  "poap.stellar.quest/*",
  "*.stellar.quest/favicon.ico",
  "*.stellar.quest/.well-known/stellar.toml"
]

[vars]
HORIZON_URL = "https://horizon-testnet.stellar.org"
STELLAR_NETWORK = "TESTNET"
SIGNER_PK = "GD4QUWBI3EIHAA5HSROV5PI7EZAJ5XU5M7EW5PZG4KRIPDCMMM5KRF4Q"

[build]
command = "pnpm build"

[site]
bucket = ".svelte-kit/assets"