name = "poapplesauce"
type = "javascript"
main = "worker-site/worker.mjs"
usage_model = "bundled"
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-06-30"

kv_namespaces = [
  { binding = "POAPS", id = "2cb8caaa6edd4cb4b60bf6c9a0c3efad" },
  { binding = "POAP_LISTS", id = "60111bbb7d35462e90ff38bb606abf0c" },
  { binding = "POAP_CLAIMS", id = "396d1a233ebd4faf95625ffe8cadd167" },
  { binding = "POAP_CODES", id = "d9729ee754674174b148fece96782106" }
]

[build]
command = "pnpm build"

[build.upload]
format = "modules"

[site]
bucket = ".svelte-kit/assets"