name = "poapplesauce"
main = "worker-site/worker.mjs"
usage_model = "bundled"
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-06-30"

kv_namespaces = [
  { binding = "POAPS", id = "2cb8caaa6edd4cb4b60bf6c9a0c3efad" },
  { binding = "POAP_LISTS", id = "60111bbb7d35462e90ff38bb606abf0c" },
  { binding = "POAP_CLAIMS", id = "396d1a233ebd4faf95625ffe8cadd167" },
  { binding = "POAP_CODES", id = "d9729ee754674174b148fece96782106" }
]

routes = [
  "poap.stellar.quest/*",
  "*.stellar.quest/favicon.ico",
  "*.stellar.quest/.well-known/stellar.toml"
]

[vars]
HORIZON_URL = "https://horizon.stellar.org"
STELLAR_NETWORK = "PUBLIC"
SIGNER_PK = "GCPFI4V3AOYQLOWDGY5UUIHG3UPZIXQWRURBH2GK5OR3AFEFXTW6BXZU"

[build]
command = "pnpm build"

[site]
bucket = ".svelte-kit/assets"

[env.testnet]
kv_namespaces = [
  { binding = "POAPS", id = "17a615c31f004bfa8771fe911bbba336" },
  { binding = "POAP_LISTS", id = "bb1f7a3ebfb048cc9d837d1c0eb02175" },
  { binding = "POAP_CLAIMS", id = "06b5b9bed81f415c94cb2d8516fef92b" },
  { binding = "POAP_CODES", id = "6e172d1186e04771955ab8f0979b3d4c" }
]
routes = [
  "poap.testnet.stellar.quest/*",
  "*.testnet.stellar.quest/favicon.ico",
  "*.testnet.stellar.quest/.well-known/stellar.toml"
]
[env.testnet.vars]
HORIZON_URL = "https://horizon-testnet.stellar.org"
STELLAR_NETWORK = "TESTNET"
SIGNER_PK = "GD4QUWBI3EIHAA5HSROV5PI7EZAJ5XU5M7EW5PZG4KRIPDCMMM5KRF4Q"
[env.testnet.build]
command = "pnpm build:dev"